### ISSUE TITLE
RuntimeWarning: invalid value encountered in log10 (windows 1.16)

### ISSUE THREAD

**Issue by zanco** [projecthorus/horus-gui#17]
Hi,
I had 2 instances running in Windows 10, 2 different radio sources, 2 diferent uploader callsigns.
This morning I noticed my pe2bz-4fsk had stopped updating on the tracker page and when arriving home one instance still was showing each decoded line but not uploading, the other one had stopped with the error message.

Last line and complete error message below:

> 2021-03-08 10:22:42,377 INFO: Habitat - Uploaded sentence: $$PE2BZ-4FSK,313,09:22:32,51.99153,4.19893,6,0,12,32,1.78*7D8B
2021-03-08 10:26:29,811 INFO: Habitat - Uploaded sentence: $$PE2BZ-4FSK,314,09:26:21,51.99152,4.19893,11,0,11,32,1.75*F951
C:\Users\pe2bz\AppData\Local\Temp\_MEI286562\horusgui\fft.py:67: RuntimeWarning: invalid value encountered in log10
2021-03-09 14:56:47,816 INFO: Stopped Audio Processing.
Traceback (most recent call last):
  File "horusgui\gui.py", line 844, in start_decoding
  File "horusgui\audio.py", line 116, in __init__
  File "lib\site-packages\pyaudio.py", line 750, in open
  File "lib\site-packages\pyaudio.py", line 441, in __init__
OSError: [Errno -9999] Unanticipated host error
Traceback (most recent call last):
  File "horusgui\gui.py", line 844, in start_decoding
  File "horusgui\audio.py", line 116, in __init__
  File "lib\site-packages\pyaudio.py", line 750, in open
  File "lib\site-packages\pyaudio.py", line 441, in __init__
OSError: [Errno -9999] Unanticipated host error
Traceback (most recent call last):
  File "horusgui\gui.py", line 844, in start_decoding
  File "horusgui\audio.py", line 116, in __init__
  File "lib\site-packages\pyaudio.py", line 750, in open
  File "lib\site-packages\pyaudio.py", line 441, in __init__
OSError: [Errno -9999] Unanticipated host error
Traceback (most recent call last):
  File "horusgui\gui.py", line 844, in start_decoding
  File "horusgui\audio.py", line 116, in __init__
  File "lib\site-packages\pyaudio.py", line 750, in open
  File "lib\site-packages\pyaudio.py", line 441, in __init__
OSError: [Errno -9999] Unanticipated host error
2021-03-09 14:57:07,467 INFO: Current configuration saved.
2021-03-09 14:57:07,893 INFO: Stopped Habitat Uploader Thread.

**Comment by darksidelemm** [comment]
The runtime warning may be causing some of the crashes, though I'm not sure its the entire issue. I'll add some additional checks for NaN values in the processing.

However the host error is something else, and is a pyaudio issue.
Another user reported issues with audio permissions under windows 10 - it may be a similar issue, but I'm not sure why it would occur mid-way through operation.

**Comment by zanco** [comment]
Hi, good catch I guess. I had 2 radio's running but the IC-705 somehow was turned off when I came home so not delivering audio to the decoder.
