### ISSUE TITLE
pyqtgraph 0.13 compatability

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/horus-gui#28]
When using PyQt5 5.15 and pyqtgraph 0.13.1 we get the error:

```
$ python3 horus-gui.py 
Traceback (most recent call last):
  File "/home/mwheeler/horus-gui/horus-gui.py", line 5, in <module>
    from horusgui.gui import *
  File "/home/mwheeler/horus-gui/horusgui/gui.py", line 28, in <module>
    from .widgets import *
  File "/home/mwheeler/horus-gui/horusgui/widgets.py", line 5, in <module>
    class QHLine(QtGui.QFrame):
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QFrame'
```

Need to check whats going on here.

**Comment by dalewegner** [comment]
Got similar error.
![pyqtgraph](https://github.com/projecthorus/horus-gui/assets/19360146/9ec38ce2-81e8-4d37-9d9e-c595b0387bd1)

**Comment by darksidelemm** [comment]
I think we're good with this now..
